services:
  web:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    image: delciocapolo/frontend-portfolio:v1
    container_name: frontend_portfolio_v1
    tty: true
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules # para evitar sobrescrever `node_modules` no contêiner
    networks:
      - portfolio_v1

networks:
  portfolio_v1:
    driver: bridge
