name: Continuous Integrations

on:
  push:
    branches:
      - main
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git default branch to main
        run: git config --global init.defaultBranch main

      - name: Cache Docker layers
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Set up Docker Compose and Install jq
        run: |
          sudo apt-get update && sudo apt-get install docker-compose -y && sudo apt-get install -y jq

      - name: Set Environment Variables
        run: |
          echo '${{ secrets.ENV_VARS }}' > env.json
          jq -r 'to_entries | .[] | "\(.key)=\(.value)"' env.json > .env

      - name: Build and Run Services
        run: |
          docker-compose -f compose.yaml up --build -d

      - name: Run tests
        run: |
          docker exec frontend_portfolio_v1 sh -c "npm run test:ci"

      - name: Upload do JUnit XML
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: test-runner/junit.xml

      - name: Check Application Logs
        run: |
          docker-compose logs

      - name: Stop and Clean Services
        if: always()
        run: docker-compose down
